# applications/minecraft/service.yaml
apiVersion: v1
kind: Service
metadata:
  name: minecraft
spec:
  type: NodePort
  selector:
    app: minecraft
  ports:
  - port: 25565
    targetPort: 25565
    protocol: TCP
    name: minecraft-tcp
  - port: 25565
    targetPort: 25565
    protocol: UDP
    name: minecraft-udp