apiVersion: v1
kind: StorageClass
metadata:
  name: minecraft-data
  namespace: minecraft
spec: 
  storageClassName: longhorn
  accessModes:
    - ReadWriteMany
  resources: 
    requests:
      storage: 250Gi