---
- name: Create temp directory for code
  file:
    path: /tmp/dbaas-build
    state: directory

- name: Copy backend code
  synchronize:
    src: "{{ playbook_dir }}/../../../applications/dbaas/backend/"
    dest: /tmp/dbaas-build/backend/


- name: Copy frontend code
  synchronize:
    src: "{{ playbook_dir }}/../../../applications/dbaas/frontend/"
    dest: /tmp/dbaas-build/frontend/
    rsync_opts:
      - "--include=public/**"
      - "--exclude=.git"
      - "--exclude=node_modules"

- name: Ensure package.json exists for frontend
  copy:
    dest: /tmp/dbaas-build/frontend/package.json
    content: |
      {
        "name": "dbaas-frontend",
        "version": "0.1.0",
        "private": true,
        "dependencies": {
          "react": "^18.2.0",
          "react-dom": "^18.2.0",
          "react-scripts": "5.0.1"
        },
        "scripts": {
          "start": "react-scripts start",
          "build": "react-scripts build",
          "test": "react-scripts test",
          "eject": "react-scripts eject"
        },
        "eslintConfig": {
          "extends": [
            "react-app"
          ]
        },
        "browserslist": {
          "production": [
            ">0.2%",
            "not dead",
            "not op_mini all"
          ],
          "development": [
            "last 1 chrome version",
            "last 1 firefox version",
            "last 1 safari version"
          ]
        }
      }
  when: not ansible_check_mode

- name: Create Dockerfile for frontend
  copy:
    dest: /tmp/dbaas-build/frontend/Dockerfile
    content: |
      # Build stage
      FROM node:16 as build
      WORKDIR /app
      COPY package*.json ./
      RUN npm install
      COPY . .
      RUN npm run build
      
      # Production stage
      FROM nginx:alpine
      COPY --from=build /app/build /usr/share/nginx/html
      EXPOSE 80
      CMD ["nginx", "-g", "daemon off;"]

- name: Build backend image
  shell: |
    docker build -t {{ registry_host }}/dbaas-backend:latest /tmp/dbaas-build/backend/
    docker save -o /tmp/dbaas-backend.tar {{ registry_host }}/dbaas-backend:latest
    k3s ctr images import /tmp/dbaas-backend.tar
  args:
    executable: /bin/bash

- name: Build frontend image
  shell: |
    docker build -t {{ registry_host }}/dbaas-frontend:latest /tmp/dbaas-build/frontend/
    docker save -o /tmp/dbaas-frontend.tar {{ registry_host }}/dbaas-frontend:latest
    k3s ctr images import /tmp/dbaas-frontend.tar
  args:
    executable: /bin/bash

- name: Clean up tarball files
  file:
    path: "{{ item }}"
    state: absent
  with_items:
    - /tmp/dbaas-backend.tar
    - /tmp/dbaas-frontend.tar

- name: Clean up build directory
  file:
    path: /tmp/dbaas-build
    state: absent
  when: not ansible_check_mode