---
- name: Create temp directory for code
  file:
    path: /tmp/dbaas-build
    state: directory

- name: Copy backend code
  synchronize:
    src: "{{ playbook_dir }}/../../backend/"
    dest: /tmp/dbaas-build/backend/

- name: Copy frontend code
  synchronize:
    src: "{{ playbook_dir }}/../../frontend/"
    dest: /tmp/dbaas-build/frontend/

- name: Ensure package.json exists for frontend
  copy:
    dest: /tmp/dbaas-build/frontend/package.json
    content: |
      {
        "name": "dbaas-frontend",
        "version": "0.1.0",
        "private": true,
        "dependencies": {
          "react": "^18.2.0",
          "react-dom": "^18.2.0",
          "react-scripts": "5.0.1"
        },
        "scripts": {
          "start": "react-scripts start",
          "build": "react-scripts build",
          "test": "react-scripts test",
          "eject": "react-scripts eject"
        },
        "eslintConfig": {
          "extends": [
            "react-app"
          ]
        },
        "browserslist": {
          "production": [
            ">0.2%",
            "not dead",
            "not op_mini all"
          ],
          "development": [
            "last 1 chrome version",
            "last 1 firefox version",
            "last 1 safari version"
          ]
        }
      }
  when: not ansible_check_mode

- name: Create Dockerfile for frontend
  copy:
    dest: /tmp/dbaas-build/frontend/Dockerfile
    content: |
      # Build stage
      FROM node:16 as build
      WORKDIR /app
      COPY package*.json ./
      RUN npm install
      COPY . .
      RUN npm run build
      
      # Production stage
      FROM nginx:alpine
      COPY --from=build /app/build /usr/share/nginx/html
      EXPOSE 80
      CMD ["nginx", "-g", "daemon off;"]

- name: Build backend image
  docker_image:
    build:
      path: /tmp/dbaas-build/backend/
    name: "{{ registry_host }}/dbaas-backend"
    tag: latest
    push: true
    source: build

- name: Build frontend image
  docker_image:
    build:
      path: /tmp/dbaas-build/frontend/
    name: "{{ registry_host }}/dbaas-frontend"
    tag: latest
    push: true
    source: build

- name: Import backend image to K3s
  command: k3s ctr images import {{ registry_host }}/dbaas-backend:latest
  register: import_backend
  changed_when: "'imported' in import_backend.stdout"
  
- name: Import frontend image to K3s
  command: k3s ctr images import {{ registry_host }}/dbaas-frontend:latest
  register: import_frontend
  changed_when: "'imported' in import_frontend.stdout"

- name: Clean up build directory
  file:
    path: /tmp/dbaas-build
    state: absent
  when: not ansible_check_mode