---
- name: Deploy HomeLab DBaaS
  hosts: server
  become: yes
  vars:
    dbaas_namespace: dbaas-system
    dbaas_domain: dbaas.local
    registry_host: localhost:5000
    flux_namespace: flux-system

  roles:
    - dbaas

  handlers:
    - name: Restart K3s
      service:
        name: k3s
        state: restarted