[server]
the-rock ansible_host=192.168.123.10 ansible_user=ubuntu

[agents]
deathwing-knight ansible_host=192.168.123.11 ansible_user=ubuntu
ravenwing-black-knight ansible_host=192.168.123.12 ansible_user=ubuntu
caliban ansible_host=127.0.0.1 ansible_connection=local

[gpu_nodes]
caliban ansible_host=127.0.0.1 ansible_connection=local

[k3s_cluster:children]
server
agents